<?php

namespace Labs\BackBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function getOneCategory($id)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where($qb->expr()->eq('c.id', ':id'));
        $qb->setParameter(':id', $id);
        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @return array
     */
    public function getSponsorByCategory()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->leftJoin('c.sponsors', 's');
        $qb->addSelect('s');
        $qb->orderBy('c.position', 'ASC');
        return $qb->getQuery()->getResult();
    }
}
