<?php

namespace Labs\BackBundle\Repository;

/**
 * AboutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserDocment($users)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->leftJoin('u.documents', 'documents');
        $qb->addSelect('documents');
        $qb->where($qb->expr()->eq('u.id', ':users'));
        $qb->setParameter(':users', $users);
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function findByRole($role)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from($this->_entityName, 'u')
            ->where('u.roles LIKE :roles')
            ->setParameter('roles', '%"'.$role.'"%');

        return $qb->getQuery()->getResult();
    }
}
