imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    gallery_directory: '%kernel.root_dir%/../web/uploads/gallery'

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   ~
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'Form/costum_form.html.twig'
# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true


stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    twig:      true
    storage:   file_system # or gaufrette or flysystem
    mappings:
        banner_image_page:
            uri_prefix:         /uploads/about
            upload_destination: "%kernel.root_dir%/../web/uploads/about"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid

        banner_image:
            uri_prefix:         /uploads/banners
            upload_destination: "%kernel.root_dir%/../web/uploads/banners"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid

        team_image:
            uri_prefix:         /uploads/teams
            upload_destination: "%kernel.root_dir%/../web/uploads/teams"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid

        partner_image:
            uri_prefix:         /uploads/partners
            upload_destination: "%kernel.root_dir%/../web/uploads/partners"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid

        blog_image:
            uri_prefix:         /uploads/posts
            upload_destination: "%kernel.root_dir%/../web/uploads/posts"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid

        blog_doc:
            uri_prefix:         /uploads/docs
            upload_destination: "%kernel.root_dir%/../web/uploads/docs"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid

        doc_file:
            uri_prefix:         /uploads/docs
            upload_destination: "%kernel.root_dir%/../web/uploads/docs"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid


fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Labs\BackBundle\Entity\Users
    from_email:
        address:        "%mailer_user%"
        sender_name:    "%mailer_sender%"
    registration:
        form:
            type: Labs\BackBundle\Form\RegistrationType

ivory_ck_editor:
    default_config: my_custom_config
    configs:
        my_custom_config:
            language: "%locale%"
            toolbar:   [ [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ], [ "About" ], "/", [ 'Bold','Italic','Underline','Strike', 'Blockquote','Subscript','Superscript','-','RemoveFormat' ], [ 'NumberedList','BulletedList','-','Outdent','Indent','-','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ], [ 'Link','Unlink','Anchor' ], '/', [ 'TextColor','BGColor' ], [ 'RemoveFormat' ], [ 'Maximize' ] ]
            uiColor:   "#FCFCFC"
            contentsCss:  ['layout_two/css/main.css']


#liip_imagine upload crop image

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        my_thumb_speakers:
            quality: 95
            filters:
                thumbnail: { size: [370, 386], mode: outbound }

        my_thumb_officel:
            quality: 95
            filters:
                thumbnail: { size: [370, 270], mode: outbound }

        my_thumb_of:
            quality: 95
            filters:
                thumbnail: { size: [360, 263], mode: outbound }

        my_thumb_off_zoom:
            quality: 95
            filters:
                thumbnail: { size: [1200, 800], mode: outbound }

        my_thumb_off_index_small:
            quality: 95
            filters:
                thumbnail: { size: [85, 85], mode: outbound }

        my_thumb_off_old:
            quality: 95
            filters:
                thumbnail: { size: [276, 250], mode: outbound }

        my_thumb_off_back:
            quality: 95
            filters:
                thumbnail: { size: [223, 223], mode: outbound }

        my_thumb_article:
            quality: 95
            filters:
                thumbnail: { size: [576, 450], mode: outbound }

        my_thumb_galerie:
            quality: 95
            filters:
                thumbnail: { size: [300, 300], mode: outbound }

        my_thumb_sponsors:
            quality: 100
            filters:
                thumbnail: { size: [211, 150], mode: outbound }

        my_thumb_sponsors_home:
            quality: 100
            filters:
                thumbnail: { size: [188, 138], mode: outbound }

        my_thumb_article_single:
            quality: 95
            filters:
                thumbnail: { size: [1200, 480], mode: outbound }

        my_thumb_profolio_full:
            quality: 100
            filters:
                relative_resize: { widen: 1200 }
                watermark:
                    image: Resources/data/logo_final.png
                    size: 0.2
                    position: bottomright

# JMS Serializer
jms_serializer:
    metadata:
        auto_detection: true