labs_member:
    resource: "@LabsMemberBundle/Controller/"
    type:     annotation
    prefix:   /accounts

labs_pages:
    resource: "@LabsPagesBundle/Controller/"
    type:     annotation
    prefix:   /

labs_back:
    resource: "@LabsBackBundle/Controller/"
    type:     annotation
    prefix:   /codepit

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"