labs_pages:
    resource: "@LabsPagesBundle/Controller/"
    type:     annotation
    prefix:   /

labs_ubold:
    resource: "@LabsUboldBundle/Controller/"
    type:     annotation
    prefix:   /tpl

labs_back:
    resource: "@LabsBackBundle/Controller/"
    type:     annotation
    prefix:   /codepit

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"