# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    draft_create:
        class: Labs\BackBundle\Services\Draft
        arguments:
            - "@doctrine.orm.entity_manager"

    labs_auth.check.error.phonenumber:
        class: Labs\BackBundle\Services\CheckErrorPhoneNumber
        arguments: ["@session","@doctrine.orm.entity_manager","@libphonenumber.phone_number_util"]

    labs_auth.app.generate_code:
        class: Labs\BackBundle\Services\GenerateService
        autowire: true